export const nombresMovimiento = {
  tienda: "Configuración",
  producto: "Producto registrado",
  editarCliente: "Cliente editado",
  corregirDeudaInicial: "Saldo previo corregido",
  anularMerma: "Merma anulada",
  anularGasto: "Gasto anulado",
  anulacionMerma: "Merma anulada",
  editarProducto: "Catálogo editado",
  archivarProducto: "Producto archivado",
  cliente: "Cliente registrado",
  deudaInicial: "Saldo previo",
  entrada: "Compra de mercadería",
  venta: "Venta",
  abono: "Abono cobrado",
  anularAbono: "Abono anulado",
  anulacionAbono: "Abono anulado",
  anularVenta: "Venta anulada",
  devolucion: "Devolución",
  merma: "Merma",
  ajusteStock: "Ajuste de existencias",
  gasto: "Gasto operativo",
  aporte: "Aporte a caja",
  retiro: "Retiro personal",
  abrirCaja: "Fondo inicial",
  apertura: "Fondo inicial",
  cerrarCaja: "Cierre",
  inventarioInicial: "Inventario inicial",
};
